CREATE  DATABASE dev;
USE dev;


CREATE TABLE IF NOT EXISTS users(
    id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ref VARCHAR(8) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL
) ENGINE = INNODB;


CREATE TABLE IF NOT EXISTS appointment (
  id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  ref VARCHAR(8) NOT NULL,
  day date NOT NULL,
  time int(1) NOT NULL,
  FOREIGN KEY (ref) REFERENCES users (ref) ON DELETE CASCADE
) ENGINE=INNODB;


